### ISSUE TITLE
iptables-legacy note in docs

### ISSUE THREAD

**Issue by WebsliceNL** [cmspam/incus-docker#2]
Is the iptables-legacy note in the docs maybe host OS dependent?

On AmazonLinux2023  iptables-legacy is not used by default by docker.

iptables-legacy -I DOCKER-USER -j ACCEPT
iptables: No chain/target/match by that name.

ip6tables-legacy -I DOCKER-USER -j ACCEPT
ip6tables: No chain/target/match by that name.

Looks like the DOCKER-USER chain is created in the new iptables tables, so I can just run;

iptables -I DOCKER-USER -j ACCEPT
ip6tables -I DOCKER-USER -j ACCEPT

iptables -L |grep DOCKER-USER
# Warning: iptables-legacy tables present, use iptables-legacy to see them
DOCKER-USER  all  --  anywhere             anywhere            
Chain DOCKER-USER (1 references)

**Comment by cmspam** [comment]
The latest docker file actually runs both in the container. Whichever one
isn’t used should error out and whichever is should work.

Depending on the OS it can be different which is used so I did it that way
for most compatibility.
